package com.geeks.ds.ProgrammingTest;

public class ExceptionDemo {

    public static void main(String[] args) {
        try{

        }catch (ArrayIndexOutOfBoundsException | ArithmeticException e){
            //e = null;

            //throw new IndexOutOfBoundsException();
            //throw new ArithmeticException();
            //throw new NullPointerException();
            //throw new ClassNotFoundException();

        }
    }
}
